#!/bin/bash
#
# Configuration file for service principal and storage account

# Service principal authentication details
export APP_ID="xxxxxxxxxxxxxxxxxxxxxxxxxxx"
export PASSWORD="xxxxxxxxxxxxxxxxxxxxxxx"
export TENANT_ID="xxxxxxxxxxxxxxxxxxxxxx"

# Storage account details
export KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
export ACCT_NAME="xxxxxxxxxxxxxxxx"
export CONTAINER_NAME="xxxxxxxxxxxxxxxx"